name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Abhängigkeiten installieren
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: MkDocs deployen
        run: |
          cd Leadify-Doku
          mkdocs gh-deploy --force